
    ##################################################
    ###   Visit https://github.com/tinybirdco/ci   ###
    ###   for more details or custom CI/CD         ###
    ##################################################

    name: Tinybird - CI Workflow

    on:
      workflow_dispatch:
      pull_request:
        branches:
          - main
          - master
        types: [opened, reopened, labeled, unlabeled, synchronize, closed]
        paths:
          - .github/workflows/tinybird*
          - dataproject/**

    concurrency: ${{ github.workflow }}-${{ github.event.pull_request.number }}

    jobs:
        ci:
          uses: tinybirdco/ci/.github/workflows/ci.yml@v4.1.0
          with:
            data_project_dir: dataproject
            tb_format: false
          secrets:
            tb_admin_token: ${{ secrets.TB_ADMIN_TOKEN }}
            tb_host: https://ui.tinybird.co
